apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-completed-pod-cleanup
rules:
- apiGroups: [""]
  resources:
     - "pods"
  verbs: ["get", "list", "create", "delete", "watch"]
